/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoodAndDrinksRouteImport } from './routes/food-and-drinks'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const FoodAndDrinksRoute = FoodAndDrinksRouteImport.update({
  id: '/food-and-drinks',
  path: '/food-and-drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/food-and-drinks': typeof FoodAndDrinksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/food-and-drinks': typeof FoodAndDrinksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/food-and-drinks': typeof FoodAndDrinksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/events' | '/food-and-drinks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/events' | '/food-and-drinks'
  id: '__root__' | '/' | '/about' | '/events' | '/food-and-drinks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  FoodAndDrinksRoute: typeof FoodAndDrinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/food-and-drinks': {
      id: '/food-and-drinks'
      path: '/food-and-drinks'
      fullPath: '/food-and-drinks'
      preLoaderRoute: typeof FoodAndDrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  FoodAndDrinksRoute: FoodAndDrinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
